from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.setFixedSize(1267, 677)
        self.centralwidget = QtWidgets.QWidget(parent=mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 1271, 701))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.label = QtWidgets.QLabel(parent=self.page)
        self.label.setGeometry(QtCore.QRect(-10, -40, 1291, 711))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/bg.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=self.page)
        self.label_5.setGeometry(QtCore.QRect(440, 430, 391, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(24)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel {\n"
"    color: white;\n"
"}")
        self.label_5.setObjectName("label_5")
        self.get_started_button = QtWidgets.QPushButton(parent=self.page)
        self.get_started_button.setGeometry(QtCore.QRect(530, 520, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(14)
        self.get_started_button.setFont(font)
        self.get_started_button.setStyleSheet("QPushButton {\n"
"    background-color: #413db8;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5f5aed;\n"
"    color: white;\n"
"}")
        self.get_started_button.setAutoDefault(False)
        self.get_started_button.setDefault(False)
        self.get_started_button.setFlat(False)
        self.get_started_button.setObjectName("get_started_button")
        self.label_6 = QtWidgets.QLabel(parent=self.page)
        self.label_6.setGeometry(QtCore.QRect(490, 210, 281, 31))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_2 = QtWidgets.QLabel(parent=self.page)
        self.label_2.setGeometry(QtCore.QRect(490, 50, 291, 91))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_7 = QtWidgets.QLabel(parent=self.page)
        self.label_7.setGeometry(QtCore.QRect(480, 150, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Palatino Linotype")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.label_3 = QtWidgets.QLabel(parent=self.page_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 1271, 651))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/road.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_10 = QtWidgets.QLabel(parent=self.page_2)
        self.label_10.setGeometry(QtCore.QRect(360, 30, 531, 81))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.login_email = QtWidgets.QLineEdit(parent=self.page_2)
        self.login_email.setGeometry(QtCore.QRect(430, 130, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.login_email.setFont(font)
        self.login_email.setObjectName("login_email")
        self.login_pword = QtWidgets.QLineEdit(parent=self.page_2)
        self.login_pword.setGeometry(QtCore.QRect(430, 230, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.login_pword.setFont(font)
        self.login_pword.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.login_pword.setObjectName("login_pword")
        self.checkBox = QtWidgets.QCheckBox(parent=self.page_2)
        self.checkBox.setGeometry(QtCore.QRect(430, 300, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.login_button = QtWidgets.QPushButton(parent=self.page_2)
        self.login_button.setGeometry(QtCore.QRect(460, 390, 331, 61))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.login_button.setFont(font)
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: #413db8;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5f5aed;\n"
"    color: white;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.label_43 = QtWidgets.QLabel(parent=self.page_2)
        self.label_43.setGeometry(QtCore.QRect(420, 490, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.create_acc_button = QtWidgets.QPushButton(parent=self.page_2)
        self.create_acc_button.setGeometry(QtCore.QRect(640, 490, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.create_acc_button.setFont(font)
        self.create_acc_button.setStyleSheet("QPushButton {\n"
"    background-color: #027a4a;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ab878;\n"
"    color: white;\n"
"}")
        self.create_acc_button.setObjectName("create_acc_button")
        self.pushButton = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/back.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.page_2)
        self.pushButton_2.setGeometry(QtCore.QRect(1230, 0, 31, 31))
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/forward.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.page_3)
        self.scrollArea.setGeometry(QtCore.QRect(0, 0, 1261, 631))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 98, 1120))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.frame.setMinimumSize(QtCore.QSize(0, 1100))
        self.frame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.number_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.number_entry.setGeometry(QtCore.QRect(240, 520, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.number_entry.setFont(font)
        self.number_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.number_entry.setObjectName("number_entry")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(240, 310, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.line_2 = QtWidgets.QFrame(parent=self.frame)
        self.line_2.setGeometry(QtCore.QRect(150, 210, 831, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(240, 170, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.frame)
        self.label_14.setGeometry(QtCore.QRect(240, 630, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.fname_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.fname_entry.setGeometry(QtCore.QRect(240, 340, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.fname_entry.setFont(font)
        self.fname_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fname_entry.setObjectName("fname_entry")
        self.label_15 = QtWidgets.QLabel(parent=self.frame)
        self.label_15.setGeometry(QtCore.QRect(240, 230, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame)
        self.label_16.setGeometry(QtCore.QRect(240, 400, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(parent=self.frame)
        self.label_17.setGeometry(QtCore.QRect(240, 730, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame)
        self.label_18.setGeometry(QtCore.QRect(240, 490, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.frame)
        self.label_19.setGeometry(QtCore.QRect(240, 560, 701, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setWordWrap(True)
        self.label_19.setObjectName("label_19")
        self.lname_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.lname_entry.setGeometry(QtCore.QRect(240, 430, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lname_entry.setFont(font)
        self.lname_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lname_entry.setObjectName("lname_entry")
        self.pword_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.pword_entry.setGeometry(QtCore.QRect(240, 760, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(7)
        self.pword_entry.setFont(font)
        self.pword_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pword_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.pword_entry.setObjectName("pword_entry")
        self.email_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.email_entry.setGeometry(QtCore.QRect(240, 660, 711, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.email_entry.setFont(font)
        self.email_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email_entry.setObjectName("email_entry")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setGeometry(QtCore.QRect(240, 260, 201, 22))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_20 = QtWidgets.QLabel(parent=self.frame)
        self.label_20.setGeometry(QtCore.QRect(240, 70, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line_3 = QtWidgets.QFrame(parent=self.frame)
        self.line_3.setGeometry(QtCore.QRect(170, 910, 831, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.signup_button = QtWidgets.QPushButton(parent=self.frame)
        self.signup_button.setGeometry(QtCore.QRect(450, 940, 281, 71))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.signup_button.setFont(font)
        self.signup_button.setStyleSheet("QPushButton {\n"
"    background-color: #027a4a;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ab878;\n"
"    color: white;\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.label_24 = QtWidgets.QLabel(parent=self.frame)
        self.label_24.setGeometry(QtCore.QRect(430, 1060, 141, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.log_back_button = QtWidgets.QPushButton(parent=self.frame)
        self.log_back_button.setGeometry(QtCore.QRect(600, 1050, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.log_back_button.setFont(font)
        self.log_back_button.setStyleSheet("QPushButton {\n"
"    background-color: #413db8;\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #5f5aed;\n"
"    color: white;\n"
"}")
        self.log_back_button.setObjectName("log_back_button")
        self.cpword_entry = QtWidgets.QLineEdit(parent=self.frame)
        self.cpword_entry.setGeometry(QtCore.QRect(240, 860, 711, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(7)
        self.cpword_entry.setFont(font)
        self.cpword_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cpword_entry.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.cpword_entry.setObjectName("cpword_entry")
        self.label_21 = QtWidgets.QLabel(parent=self.frame)
        self.label_21.setGeometry(QtCore.QRect(240, 830, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_2.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.label_44 = QtWidgets.QLabel(parent=self.page_4)
        self.label_44.setGeometry(QtCore.QRect(220, 30, 781, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        self.label_44.setFont(font)
        self.label_44.setWordWrap(True)
        self.label_44.setObjectName("label_44")
        self.host_button = QtWidgets.QPushButton(parent=self.page_4)
        self.host_button.setGeometry(QtCore.QRect(530, 100, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.host_button.setFont(font)
        self.host_button.setStyleSheet("QPushButton {        \n"
"    background-color: rgb(87, 75, 255);\n"
"    border-radius: 10px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(139, 135, 255);\n"
"    color: white\n"
"}")
        self.host_button.setObjectName("host_button")
        self.logout_button = QtWidgets.QPushButton(parent=self.page_4)
        self.logout_button.setGeometry(QtCore.QRect(1160, 10, 89, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(8)
        self.logout_button.setFont(font)
        self.logout_button.setStyleSheet("QPushButton {        \n"
"    background-color: rgb(255, 25, 55);\n"
"    border-radius: 5px;\n"
"    color: white\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 107, 122);\n"
"    color: white\n"
"}")
        self.logout_button.setObjectName("logout_button")
        self.car_list_frame = QtWidgets.QFrame(parent=self.page_4)
        self.car_list_frame.setGeometry(QtCore.QRect(210, 160, 841, 471))
        self.car_list_frame.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.car_list_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.car_list_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.car_list_frame.setObjectName("car_list_frame")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.scrollArea_2 = QtWidgets.QScrollArea(parent=self.page_5)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 20, 1241, 609))
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 98, 1520))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 1500))
        self.frame_2.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_31 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_31.setGeometry(QtCore.QRect(240, 30, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.license_num_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.license_num_entry.setGeometry(QtCore.QRect(240, 160, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.license_num_entry.setFont(font)
        self.license_num_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.license_num_entry.setObjectName("license_num_entry")
        self.label_32 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_32.setGeometry(QtCore.QRect(240, 130, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_33.setGeometry(QtCore.QRect(240, 230, 531, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.car_model_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.car_model_entry.setGeometry(QtCore.QRect(240, 360, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.car_model_entry.setFont(font)
        self.car_model_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.car_model_entry.setObjectName("car_model_entry")
        self.label_34 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(240, 330, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.checkBox_4 = QtWidgets.QCheckBox(parent=self.frame_2)
        self.checkBox_4.setGeometry(QtCore.QRect(240, 500, 361, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.submit_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.submit_button.setGeometry(QtCore.QRect(440, 1330, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.submit_button.setFont(font)
        self.submit_button.setStyleSheet("QPushButton {\n"
"    background-color: green;\n"
"    color: white;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1ab878;\n"
"    color: white;\n"
"}")
        self.submit_button.setObjectName("submit_button")
        self.label_35 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(240, 430, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.car_number_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.car_number_entry.setGeometry(QtCore.QRect(240, 460, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.car_number_entry.setFont(font)
        self.car_number_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.car_number_entry.setObjectName("car_number_entry")
        self.seats_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.seats_entry.setGeometry(QtCore.QRect(240, 580, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.seats_entry.setFont(font)
        self.seats_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.seats_entry.setText("")
        self.seats_entry.setObjectName("seats_entry")
        self.label_36 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(240, 550, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_37.setGeometry(QtCore.QRect(240, 650, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.pickup_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.pickup_entry.setGeometry(QtCore.QRect(240, 680, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.pickup_entry.setFont(font)
        self.pickup_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.pickup_entry.setObjectName("pickup_entry")
        self.label_38 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_38.setGeometry(QtCore.QRect(240, 750, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.contact_info_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.contact_info_entry.setGeometry(QtCore.QRect(240, 780, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.contact_info_entry.setFont(font)
        self.contact_info_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.contact_info_entry.setText("")
        self.contact_info_entry.setObjectName("contact_info_entry")
        self.transmission_combo = QtWidgets.QComboBox(parent=self.frame_2)
        self.transmission_combo.setGeometry(QtCore.QRect(240, 1080, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.transmission_combo.setFont(font)
        self.transmission_combo.setEditable(False)
        self.transmission_combo.setObjectName("transmission_combo")
        self.transmission_combo.addItem("")
        self.transmission_combo.addItem("")
        self.transmission_combo.addItem("")
        self.transmission_combo.addItem("")
        self.label_45 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_45.setGeometry(QtCore.QRect(240, 1050, 251, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_3.setGeometry(QtCore.QRect(1170, 0, 31, 31))
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/forward.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(0, 0, 31, 31))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/back.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.dateEdit = QtWidgets.QDateEdit(parent=self.frame_2)
        self.dateEdit.setGeometry(QtCore.QRect(240, 260, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        self.dateEdit.setFont(font)
        self.dateEdit.setObjectName("dateEdit")
        self.label_39 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_39.setGeometry(QtCore.QRect(240, 1160, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.image_path_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.image_path_entry.setGeometry(QtCore.QRect(240, 1200, 461, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.image_path_entry.setFont(font)
        self.image_path_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.image_path_entry.setText("")
        self.image_path_entry.setObjectName("image_path_entry")
        self.line = QtWidgets.QFrame(parent=self.frame_2)
        self.line.setGeometry(QtCore.QRect(20, 1290, 1161, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.upload_button = QtWidgets.QPushButton(parent=self.frame_2)
        self.upload_button.setGeometry(QtCore.QRect(720, 1200, 171, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.upload_button.setFont(font)
        self.upload_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(34, 152, 255);\n"
"    color: white;\n"
"    border-radius: 10px\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(126, 156, 255);\n"
"    color: white;\n"
"}")
        self.upload_button.setObjectName("upload_button")
        self.label_40 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_40.setGeometry(QtCore.QRect(240, 850, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.price_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.price_entry.setGeometry(QtCore.QRect(240, 880, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.price_entry.setFont(font)
        self.price_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.price_entry.setText("")
        self.price_entry.setObjectName("price_entry")
        self.label_41 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_41.setGeometry(QtCore.QRect(240, 940, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.odometer_entry = QtWidgets.QLineEdit(parent=self.frame_2)
        self.odometer_entry.setGeometry(QtCore.QRect(240, 970, 651, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.odometer_entry.setFont(font)
        self.odometer_entry.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.odometer_entry.setText("")
        self.odometer_entry.setObjectName("odometer_entry")
        self.verticalLayout_3.addWidget(self.frame_2)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.frame_3 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 1271, 61))
        self.frame_3.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_4.setGeometry(QtCore.QRect(50, 0, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_5.setGeometry(QtCore.QRect(1230, 20, 31, 31))
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/forward.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.frame_3)
        self.pushButton_6.setGeometry(QtCore.QRect(0, 20, 31, 31))
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/back.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.frame_4 = QtWidgets.QFrame(parent=self.page_6)
        self.frame_4.setGeometry(QtCore.QRect(0, 120, 1281, 521))
        self.frame_4.setStyleSheet("background-color: rgb(231, 231, 231);\n"
"border-radius: 5px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(81, 231, 16, 16))
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_22 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_22.setGeometry(QtCore.QRect(386, 231, 16, 16))
        self.label_22.setText("")
        self.label_22.setObjectName("label_22")
        self.frame_11 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_11.setGeometry(QtCore.QRect(830, 10, 341, 91))
        self.frame_11.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_11.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_11.setObjectName("frame_11")
        self.label_55 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_55.setGeometry(QtCore.QRect(10, 10, 121, 61))
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/sample_car.png"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_56.setGeometry(QtCore.QRect(130, 40, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(parent=self.frame_11)
        self.label_57.setGeometry(QtCore.QRect(130, 60, 211, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_57.setFont(font)
        self.label_57.setStyleSheet("color: rgb(34, 124, 94);")
        self.label_57.setObjectName("label_57")
        self.total_frame = QtWidgets.QFrame(parent=self.frame_11)
        self.total_frame.setGeometry(QtCore.QRect(140, 0, 161, 41))
        self.total_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.total_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.total_frame.setObjectName("total_frame")
        self.total_label = QtWidgets.QLabel(parent=self.total_frame)
        self.total_label.setGeometry(QtCore.QRect(0, 0, 161, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.total_label.setFont(font)
        self.total_label.setText("")
        self.total_label.setObjectName("total_label")
        self.checkout_button = QtWidgets.QPushButton(parent=self.frame_4)
        self.checkout_button.setGeometry(QtCore.QRect(920, 430, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.checkout_button.setFont(font)
        self.checkout_button.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 43, 57);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 87, 90);\n"
"    color: white;\n"
"}")
        self.checkout_button.setObjectName("checkout_button")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_4)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 140, 1101, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.frame_6 = QtWidgets.QFrame(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.frame_6.setFont(font)
        self.frame_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_23 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.label_29 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_29.setGeometry(QtCore.QRect(20, 100, 21, 21))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_29.setScaledContents(True)
        self.label_29.setObjectName("label_29")
        self.pack1_check = QtWidgets.QCheckBox(parent=self.frame_6)
        self.pack1_check.setGeometry(QtCore.QRect(20, 190, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pack1_check.setFont(font)
        self.pack1_check.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 43, 57);")
        self.pack1_check.setObjectName("pack1_check")
        self.label_26 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_26.setGeometry(QtCore.QRect(20, 61, 21, 21))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_27.setGeometry(QtCore.QRect(51, 61, 159, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(parent=self.frame_6)
        self.label_28.setGeometry(QtCore.QRect(51, 100, 155, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.gridLayout_4.addWidget(self.frame_6, 0, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.frame_9.setFont(font)
        self.frame_9.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_48 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_48.setGeometry(QtCore.QRect(10, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_49.setGeometry(QtCore.QRect(20, 50, 21, 21))
        self.label_49.setText("")
        self.label_49.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_49.setScaledContents(True)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_50.setGeometry(QtCore.QRect(20, 90, 21, 21))
        self.label_50.setText("")
        self.label_50.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_50.setScaledContents(True)
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_51.setGeometry(QtCore.QRect(20, 130, 21, 21))
        self.label_51.setText("")
        self.label_51.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_51.setScaledContents(True)
        self.label_51.setObjectName("label_51")
        self.pack3_check = QtWidgets.QCheckBox(parent=self.frame_9)
        self.pack3_check.setGeometry(QtCore.QRect(20, 190, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pack3_check.setFont(font)
        self.pack3_check.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 43, 57);")
        self.pack3_check.setObjectName("pack3_check")
        self.label_53 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_53.setGeometry(QtCore.QRect(50, 129, 155, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_52 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_52.setGeometry(QtCore.QRect(50, 51, 98, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_54 = QtWidgets.QLabel(parent=self.frame_9)
        self.label_54.setGeometry(QtCore.QRect(50, 90, 149, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.gridLayout_4.addWidget(self.frame_9, 0, 2, 1, 1)
        self.frame_7 = QtWidgets.QFrame(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        self.frame_7.setFont(font)
        self.frame_7.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.label_25 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.label_30 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_30.setGeometry(QtCore.QRect(20, 60, 21, 21))
        self.label_30.setText("")
        self.label_30.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_30.setScaledContents(True)
        self.label_30.setObjectName("label_30")
        self.label_42 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_42.setGeometry(QtCore.QRect(20, 100, 21, 21))
        self.label_42.setText("")
        self.label_42.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/check.png"))
        self.label_42.setScaledContents(True)
        self.label_42.setObjectName("label_42")
        self.pack2_check = QtWidgets.QCheckBox(parent=self.frame_7)
        self.pack2_check.setGeometry(QtCore.QRect(20, 190, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pack2_check.setFont(font)
        self.pack2_check.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(255, 43, 57);")
        self.pack2_check.setObjectName("pack2_check")
        self.label_46 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_46.setGeometry(QtCore.QRect(50, 61, 98, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(parent=self.frame_7)
        self.label_47.setGeometry(QtCore.QRect(50, 102, 155, 21))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.gridLayout_4.addWidget(self.frame_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.page_6)
        self.label_8.setGeometry(QtCore.QRect(80, 80, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.page_6)
        self.label_9.setGeometry(QtCore.QRect(50, 90, 21, 21))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("C:\\Users\\wired\\Desktop\\udemy\\mass-projects\\car-rental\\ui\\../img/protection.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.scrollArea_3 = QtWidgets.QScrollArea(parent=self.page_7)
        self.scrollArea_3.setGeometry(QtCore.QRect(0, 0, 1261, 651))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1239, 1520))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_12 = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents_4)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 1500))
        self.frame_12.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_12.setObjectName("frame_12")
        self.frame_13 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_13.setGeometry(QtCore.QRect(-10, -10, 1271, 61))
        self.frame_13.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_13.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_58 = QtWidgets.QLabel(parent=self.frame_13)
        self.label_58.setGeometry(QtCore.QRect(70, 0, 271, 61))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.pushButton_7 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_7.setGeometry(QtCore.QRect(1200, 20, 31, 31))
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/forward.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.frame_13)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border-image: url(C:/Users/wired/Desktop/udemy/mass-projects/car-rental/img/back.png);\n"
"    background: none;\n"
"    border: none;\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:hover {\n"
"    opacity: 1;\n"
"}\n"
"QPushButton:pressed {\n"
"    opacity: 1.2;\n"
"}\n"
"")
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.frame_14 = QtWidgets.QFrame(parent=self.frame_12)
        self.frame_14.setGeometry(QtCore.QRect(0, 60, 1251, 1461))
        self.frame_14.setStyleSheet("background-color: rgb(231, 231, 231);")
        self.frame_14.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_59 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_59.setGeometry(QtCore.QRect(140, 20, 291, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.line_4 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_4.setGeometry(QtCore.QRect(140, 70, 921, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.checkBox_2 = QtWidgets.QCheckBox(parent=self.frame_14)
        self.checkBox_2.setGeometry(QtCore.QRect(380, 290, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.label_64 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_64.setGeometry(QtCore.QRect(140, 460, 228, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_65.setGeometry(QtCore.QRect(140, 510, 228, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_66.setGeometry(QtCore.QRect(140, 550, 228, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setObjectName("label_66")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.frame_14)
        self.lineEdit_5.setGeometry(QtCore.QRect(370, 460, 455, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.frame_14)
        self.lineEdit_6.setGeometry(QtCore.QRect(370, 550, 151, 27))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.dateEdit_2 = QtWidgets.QDateEdit(parent=self.frame_14)
        self.dateEdit_2.setGeometry(QtCore.QRect(370, 510, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.dateEdit_2.setFont(font)
        self.dateEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dateEdit_2.setObjectName("dateEdit_2")
        self.label_67 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_67.setGeometry(QtCore.QRect(140, 380, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_67.setFont(font)
        self.label_67.setObjectName("label_67")
        self.label_68 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_68.setGeometry(QtCore.QRect(140, 610, 911, 71))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_68.setFont(font)
        self.label_68.setWordWrap(True)
        self.label_68.setObjectName("label_68")
        self.line_5 = QtWidgets.QFrame(parent=self.frame_14)
        self.line_5.setGeometry(QtCore.QRect(140, 720, 921, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.label_69 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_69.setGeometry(QtCore.QRect(140, 730, 541, 61))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed")
        font.setPointSize(24)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(parent=self.frame_14)
        self.label_70.setGeometry(QtCore.QRect(140, 780, 911, 81))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_70.setFont(font)
        self.label_70.setWordWrap(True)
        self.label_70.setObjectName("label_70")
        self.terms_check = QtWidgets.QCheckBox(parent=self.frame_14)
        self.terms_check.setGeometry(QtCore.QRect(140, 1270, 601, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.terms_check.setFont(font)
        self.terms_check.setObjectName("terms_check")
        self.reserve_button = QtWidgets.QPushButton(parent=self.frame_14)
        self.reserve_button.setGeometry(QtCore.QRect(790, 1270, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.reserve_button.setFont(font)
        self.reserve_button.setStyleSheet("QPushButton {\n"
"    background-color:  rgb(255, 43, 57);\n"
"    color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(255, 87, 90);\n"
"    color: white;\n"
"}")
        self.reserve_button.setObjectName("reserve_button")
        self.frame_15 = QtWidgets.QFrame(parent=self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(140, 900, 911, 291))
        self.frame_15.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_71 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_71.setGeometry(QtCore.QRect(0, -10, 911, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_71.setFont(font)
        self.label_71.setWordWrap(True)
        self.label_71.setObjectName("label_71")
        self.label_72 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_72.setGeometry(QtCore.QRect(0, 80, 911, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_72.setFont(font)
        self.label_72.setWordWrap(True)
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_73.setGeometry(QtCore.QRect(0, 150, 911, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_73.setFont(font)
        self.label_73.setWordWrap(True)
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(parent=self.frame_15)
        self.label_74.setGeometry(QtCore.QRect(0, 210, 911, 61))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_74.setFont(font)
        self.label_74.setWordWrap(True)
        self.label_74.setObjectName("label_74")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_14)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 100, 921, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_60 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.gridLayout_5.addWidget(self.label_60, 0, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_5.addWidget(self.lineEdit, 0, 1, 1, 1)
        self.label_62 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.gridLayout_5.addWidget(self.label_62, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.label_61 = QtWidgets.QLabel(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.gridLayout_5.addWidget(self.label_61, 2, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 2, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_5.setColumnStretch(1, 3)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.frame_14)
        self.layoutWidget2.setGeometry(QtCore.QRect(140, 250, 691, 29))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_63 = QtWidgets.QLabel(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.gridLayout_6.addWidget(self.label_63, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.layoutWidget2)
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_6.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.gridLayout_6.setColumnStretch(0, 1)
        self.gridLayout_6.setColumnStretch(1, 2)
        self.verticalLayout_4.addWidget(self.frame_12)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.stackedWidget.addWidget(self.page_7)
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1267, 25))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "EZDrive Ghana"))
        self.label_5.setText(_translate("mainWindow", "We\'ve got you covered"))
        self.get_started_button.setText(_translate("mainWindow", "Get Started"))
        self.label_6.setText(_translate("mainWindow", "Rent just about any car, just about anywhere"))
        self.label_2.setText(_translate("mainWindow", "EZDrive Ghana"))
        self.label_7.setText(_translate("mainWindow", "Skip the rental car counter"))
        self.label_10.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:26pt;\">LOG INTO YOUR EZDRIVE ACCOUNT</span></p></body></html>"))
        self.login_email.setPlaceholderText(_translate("mainWindow", "Email"))
        self.login_pword.setPlaceholderText(_translate("mainWindow", "Password(case sensitive)"))
        self.checkBox.setText(_translate("mainWindow", "Remember Me"))
        self.login_button.setText(_translate("mainWindow", "LOG IN"))
        self.label_43.setText(_translate("mainWindow", "Need an account ?"))
        self.create_acc_button.setText(_translate("mainWindow", "Create one now"))
        self.label_12.setText(_translate("mainWindow", "First Name (As it appears on your Driver\'s License)"))
        self.label_13.setText(_translate("mainWindow", "Let\'s get your personal account details"))
        self.label_14.setText(_translate("mainWindow", "Email Address"))
        self.label_15.setText(_translate("mainWindow", "Region"))
        self.label_16.setText(_translate("mainWindow", "Last Name (As it appears on your Driver\'s License)"))
        self.label_17.setText(_translate("mainWindow", "Password"))
        self.label_18.setText(_translate("mainWindow", "Mobile Number"))
        self.label_19.setText(_translate("mainWindow", "If you provide your mobile phone number you can opt-in to receiving text messages about your reservations."))
        self.pword_entry.setPlaceholderText(_translate("mainWindow", "minimum of 8 characters"))
        self.comboBox.setCurrentText(_translate("mainWindow", "Greater Accra"))
        self.comboBox.setItemText(0, _translate("mainWindow", "Greater Accra"))
        self.comboBox.setItemText(1, _translate("mainWindow", "Oti"))
        self.comboBox.setItemText(2, _translate("mainWindow", "Bono East"))
        self.comboBox.setItemText(3, _translate("mainWindow", "Ahafo"))
        self.comboBox.setItemText(4, _translate("mainWindow", "Bono"))
        self.comboBox.setItemText(5, _translate("mainWindow", "North East"))
        self.comboBox.setItemText(6, _translate("mainWindow", "Savannah"))
        self.comboBox.setItemText(7, _translate("mainWindow", "Western North"))
        self.comboBox.setItemText(8, _translate("mainWindow", "Western"))
        self.comboBox.setItemText(9, _translate("mainWindow", "Volta"))
        self.comboBox.setItemText(10, _translate("mainWindow", "Eastern"))
        self.comboBox.setItemText(11, _translate("mainWindow", "Ashanti"))
        self.comboBox.setItemText(12, _translate("mainWindow", "Central"))
        self.comboBox.setItemText(13, _translate("mainWindow", "Northern"))
        self.comboBox.setItemText(14, _translate("mainWindow", "Upper East"))
        self.comboBox.setItemText(15, _translate("mainWindow", "Upper West"))
        self.label_20.setText(_translate("mainWindow", "<html><head/><body><p>JOIN EZDRIVE PREFERRED</p></body></html>"))
        self.signup_button.setText(_translate("mainWindow", "SIGN UP"))
        self.label_24.setText(_translate("mainWindow", "Login Instead:"))
        self.log_back_button.setText(_translate("mainWindow", "Log back in"))
        self.cpword_entry.setPlaceholderText(_translate("mainWindow", "make sure your passwords match"))
        self.label_21.setText(_translate("mainWindow", "Confirm Password"))
        self.label_44.setText(_translate("mainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Whether you want to host a few cars to earn extra income to pay for life’s expenses, or build a small shop with a portfolio of cars, start with one car and scale how you want.</span></p></body></html>"))
        self.host_button.setText(_translate("mainWindow", "BECOME A HOST"))
        self.logout_button.setText(_translate("mainWindow", "LOG OUT"))
        self.label_31.setText(_translate("mainWindow", "<html><head/><body><p>LIST YOUR CAR</p></body></html>"))
        self.label_32.setText(_translate("mainWindow", "Driver\'s License Number"))
        self.label_33.setText(_translate("mainWindow", "Car Availability (Date showing when the car is available.)"))
        self.label_34.setText(_translate("mainWindow", "Car Model"))
        self.checkBox_4.setText(_translate("mainWindow", "Car Insurance Availability"))
        self.submit_button.setText(_translate("mainWindow", "Submit Listing"))
        self.label_35.setText(_translate("mainWindow", "Car Number Registered on Plate"))
        self.label_36.setText(_translate("mainWindow", "Number of Seats"))
        self.label_37.setText(_translate("mainWindow", "Pickup Location"))
        self.label_38.setText(_translate("mainWindow", "Contact Information (How can renters can reach you)"))
        self.transmission_combo.setStyleSheet(_translate("mainWindow", "background-color: rgb(255, 255, 255);"))
        self.transmission_combo.setCurrentText(_translate("mainWindow", "Manual Transmission"))
        self.transmission_combo.setItemText(0, _translate("mainWindow", "Manual Transmission"))
        self.transmission_combo.setItemText(1, _translate("mainWindow", "Torque Converter Automatic"))
        self.transmission_combo.setItemText(2, _translate("mainWindow", "CVT Automatic"))
        self.transmission_combo.setItemText(3, _translate("mainWindow", "DCT Automatic"))
        self.label_45.setText(_translate("mainWindow", "Transmission Type"))
        self.dateEdit.setStyleSheet(_translate("mainWindow", "background-color: rgb(255, 255, 255);"))
        self.label_39.setText(_translate("mainWindow", "Upload your car images here (upload up to 5 images)"))
        self.image_path_entry.setPlaceholderText(_translate("mainWindow", "image path here..."))
        self.upload_button.setText(_translate("mainWindow", "Upload Image"))
        self.label_40.setText(_translate("mainWindow", "Price Per Day (GH₵, without any commas)"))
        self.label_41.setText(_translate("mainWindow", "Odometer (Distance traveled by the vehicle)"))
        self.label_4.setText(_translate("mainWindow", "EZDrive Ghana"))
        self.label_56.setText(_translate("mainWindow", "Including taxes, fees and surchages"))
        self.label_57.setText(_translate("mainWindow", "Unlimited free kilometers"))
        self.checkout_button.setText(_translate("mainWindow", "PROCEED TO CHECKOUT"))
        self.label_23.setText(_translate("mainWindow", "Road Warrior Package"))
        self.pack1_check.setText(_translate("mainWindow", "GH₵450/DAY"))
        self.label_27.setText(_translate("mainWindow", "Hands-Free Navigation"))
        self.label_28.setText(_translate("mainWindow", "Cover Roadside Issues"))
        self.label_48.setText(_translate("mainWindow", "Protection & Data Package"))
        self.pack3_check.setText(_translate("mainWindow", "GH₵950/DAY"))
        self.label_53.setText(_translate("mainWindow", "Cover Roadside Issues"))
        self.label_52.setText(_translate("mainWindow", "Cover The Car"))
        self.label_54.setText(_translate("mainWindow", "Travel Tab Adventurer"))
        self.label_25.setText(_translate("mainWindow", "Protection & Safety Package"))
        self.pack2_check.setText(_translate("mainWindow", "GH₵520/DAY"))
        self.label_46.setText(_translate("mainWindow", "Cover The Car"))
        self.label_47.setText(_translate("mainWindow", "Cover Roadside Issues"))
        self.label_8.setText(_translate("mainWindow", "Protection & Coverages"))
        self.label_58.setText(_translate("mainWindow", "EZDrive Ghana"))
        self.label_59.setText(_translate("mainWindow", "<html><head/><body><p>YOUR INFORMATION</p></body></html>"))
        self.checkBox_2.setText(_translate("mainWindow", "Yes, I want to recieve text messages regarding my current and upcoming rentals"))
        self.label_64.setText(_translate("mainWindow", "Card Number"))
        self.label_65.setText(_translate("mainWindow", "Expiration Date"))
        self.label_66.setText(_translate("mainWindow", "Security Code(CVV/CVC)"))
        self.label_67.setText(_translate("mainWindow", "<html><head/><body><p>CREDIT CARD &amp; BILLING INFORMATION</p></body></html>"))
        self.label_68.setText(_translate("mainWindow", "Credit cards are the recommended form of payment to complete your \"Pay Now\" reservation. Debit cards are not accepted at many EZDrive locations. Please note: At the time of rental, there will be a hold amount of up to GH₵950 for credit and debit cards."))
        self.label_69.setText(_translate("mainWindow", "<html><head/><body><p>TERMS AND CONDITIONS</p></body></html>"))
        self.label_70.setText(_translate("mainWindow", "IMPORTANT:  Please read the following terms for your prepaid reservation carefully. Cancellation and No-Show charges may reduce refunds for prepaid reservations. Once the vehicle is rented there are no refunds or credits for unused rental days. The below terms apply to all rentals within the Ghana."))
        self.terms_check.setText(_translate("mainWindow", "I have read and accepted the Prepaid Policies and the Rental Terms and Conditions"))
        self.reserve_button.setText(_translate("mainWindow", "RESERVE"))
        self.label_71.setText(_translate("mainWindow", "*Cancelling up to 24 hours prior to scheduled pickup time, you will receive a refund of your prepaid amount, minus a GH₵250.00 cancellation fee."))
        self.label_72.setText(_translate("mainWindow", "*Cancelling within 24 hours prior to the scheduled pickup time, You will receive a refund of your prepaid amount, minus a GH₵250.00 cancellation fee. If your prepaid amount is less than GH₵250.00 no refund will be issued."))
        self.label_73.setText(_translate("mainWindow", "*No show, or failure to pick-up your rental vehicle, no refund will be issued"))
        self.label_74.setText(_translate("mainWindow", "*Rental is picked up, but returned early, no refund will be issued"))
        self.label_60.setText(_translate("mainWindow", "First Name"))
        self.label_62.setText(_translate("mainWindow", "Last Name"))
        self.label_61.setText(_translate("mainWindow", "Email"))
        self.label_63.setText(_translate("mainWindow", "Mobile Number"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
